# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=100)),
                ('block_img', models.ImageField(blank=True, upload_to='')),
                ('block_info', models.TextField(blank=True)),
                ('block_tip', models.TextField(help_text='블럭별 팁을 입력', verbose_name='Tip!')),
            ],
        ),
        migrations.CreateModel(
            name='Blockview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_img', models.ImageField(blank=True, upload_to='')),
                ('blocks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yagudjango.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Gujang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='gujang', max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('content', models.TextField(help_text='구장 기본적인 정보 입력')),
                ('basic', models.ImageField(blank=True, upload_to='')),
                ('cheer', models.ImageField(blank=True, upload_to='')),
                ('sight', models.ImageField(blank=True, upload_to='')),
                ('etc', models.ImageField(blank=True, upload_to='')),
                ('tip', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yagudjango.Gujang'),
        ),
    ]
