# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yagudjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gujang',
            name='line',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
