# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yagudjango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gujang',
            name='sight_overall',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='gujang',
            name='sight_real',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
