# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yagudjango', '0002_auto_20170213_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_tip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='block_point',
            field=models.CharField(blank=True, help_text='해당 블럭의 좌표를 입력해주세요', max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yagudjango.Block'),
        ),
    ]
