# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yagudjango', '0002_gujang_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gujang',
            name='tag_set',
        ),
        migrations.AddField(
            model_name='block',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='yagudjango.Tag'),
        ),
    ]
