# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yagudjango', '0003_auto_20170213_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='gujang',
            name='tag_at',
            field=models.ManyToManyField(blank=True, to='yagudjango.Tag'),
        ),
    ]
