# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yagudjango', '0004_gujang_tag_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('is_blind', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='blockview',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='block',
            name='block',
        ),
        migrations.AddField(
            model_name='block',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yagudjango.Gujang', verbose_name='구장'),
        ),
        migrations.DeleteModel(
            name='Blockview',
        ),
        migrations.AddField(
            model_name='seat',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yagudjango.Block'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set([('block', 'row', 'col')]),
        ),
    ]
