# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yagudjango', '0005_auto_20170214_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='block_img',
        ),
    ]
