# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yagudjango', '0006_remove_block_block_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_img', models.ImageField(upload_to='')),
                ('blocks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yagudjango.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Imgtext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_text', models.TextField(blank=True)),
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yagudjango.Blockimg')),
            ],
        ),
    ]
