# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_name', models.CharField(max_length=100)),
                ('block_point', models.CharField(blank=True, help_text='해당 블럭의 좌표를 입력해주세요', max_length=200)),
                ('block_info', models.TextField(blank=True)),
                ('block_tip', models.TextField(help_text='블럭별 팁을 입력', verbose_name='Tip!')),
            ],
        ),
        migrations.CreateModel(
            name='Blockimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_img', models.ImageField(upload_to='')),
                ('blocks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yagudjango.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yagudjango.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Gujang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='gujang', max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='')),
                ('content', models.TextField(help_text='구장 기본적인 정보 입력')),
                ('basic', models.ImageField(blank=True, upload_to='')),
                ('cheer', models.ImageField(blank=True, upload_to='')),
                ('sight', models.ImageField(blank=True, upload_to='')),
                ('sight_real', models.ImageField(blank=True, upload_to='')),
                ('sight_overall', models.ImageField(blank=True, upload_to='')),
                ('etc', models.ImageField(blank=True, upload_to='')),
                ('tip', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imgtext',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_text', models.TextField(blank=True)),
                ('text', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='yagudjango.Blockimg')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveIntegerField()),
                ('col', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('is_blind', models.BooleanField(default=False)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yagudjango.Block')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_tip', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='gujang',
            name='tag_set',
            field=models.ManyToManyField(blank=True, to='yagudjango.Tag'),
        ),
        migrations.AddField(
            model_name='block',
            name='stadium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='yagudjango.Gujang', verbose_name='구장'),
        ),
        migrations.AlterUniqueTogether(
            name='seat',
            unique_together=set([('block', 'row', 'col')]),
        ),
    ]
