# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yagudjango', '0003_auto_20170215_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgtext',
            name='text',
        ),
        migrations.AddField(
            model_name='blockimg',
            name='img_caption',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Imgtext',
        ),
    ]
