# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 08:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20170206_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='view_img',
            new_name='block_view',
        ),
    ]
