# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170206_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gujang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(default='None/no_img.png', upload_to='/')),
                ('content', models.TextField(help_text='구장 기본적인 정보 입력')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('basic', models.ImageField(default='None/no_img.png', upload_to='/')),
                ('cheer', models.ImageField(default='None/no_img.png', upload_to='/')),
                ('sight', models.ImageField(default='None/no_img.png', upload_to='/')),
                ('etc', models.ImageField(default='None/no_img.png', upload_to='/')),
                ('tag', models.TextField(help_text='해시태그 형태로 구장별 팁을 제공')),
            ],
        ),
    ]
