# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 06:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_gujang_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_img', models.ImageField(blank=True, default='None/no_img.png', upload_to='c:/pro')),
            ],
        ),
        migrations.RemoveField(
            model_name='block',
            name='block_view',
        ),
        migrations.AlterField(
            model_name='block',
            name='block_img',
            field=models.ImageField(default='None/no_img.png', upload_to='c:/pro'),
        ),
        migrations.AlterField(
            model_name='gujang',
            name='content',
            field=models.TextField(default='준비중', help_text='구장 기본적인 정보 입력'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='basic',
            field=models.ImageField(blank=True, default='None/no_img.png', upload_to='c:/pro'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='cheer',
            field=models.ImageField(blank=True, default='None/no_img.png', upload_to='c:/pro'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='etc',
            field=models.ImageField(blank=True, default='None/no_img.png', upload_to='c:/pro'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='sight',
            field=models.ImageField(blank=True, default='None/no_img.png', upload_to='c:/pro'),
        ),
        migrations.AddField(
            model_name='blockview',
            name='block_view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Block'),
        ),
    ]
