# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 00:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170207_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockview',
            name='block_view',
        ),
        migrations.AddField(
            model_name='blockview',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Block'),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_img',
            field=models.ImageField(default='None/no_img.png', upload_to='pro/askdjango'),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_info',
            field=models.TextField(default='info', help_text='블럭기본정보입력', verbose_name='블럭정보'),
        ),
        migrations.AlterField(
            model_name='blockview',
            name='view_img',
            field=models.ImageField(default='pro/askdjango/None/no_img.png', upload_to='pro/askdjango'),
        ),
        migrations.AlterField(
            model_name='gujang',
            name='content',
            field=models.TextField(help_text='구장 기본적인 정보 입력'),
        ),
        migrations.AlterField(
            model_name='gujang',
            name='logo',
            field=models.ImageField(default='None/no_img.png', upload_to='pro/askdjango'),
        ),
        migrations.AlterField(
            model_name='gujang',
            name='name',
            field=models.CharField(default='gujang', max_length=100),
        ),
        migrations.AlterField(
            model_name='theme',
            name='basic',
            field=models.ImageField(default='pro/askdjango/None/no_img.png', upload_to='pro/askdjango'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='cheer',
            field=models.ImageField(default='pro/askdjango/None/no_img.png', upload_to='pro/askdjango'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='etc',
            field=models.ImageField(default='pro/askdjango/None/no_img.png', upload_to='pro/askdjango'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='sight',
            field=models.ImageField(default='pro/askdjango/None/no_img.png', upload_to='pro/askdjango'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='tag',
            field=models.TextField(blank=True, help_text='해시태그 형태로 구장별 팁을 제공'),
        ),
    ]
