# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20170209_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gujang',
            name='logo',
            field=models.ImageField(default='pro/askdjango/project/logo/None/no_img.png', upload_to='pro/askdjango/project/logo'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='basic',
            field=models.ImageField(default='pro/askdjango/None/no_img.png', upload_to='pro/askdjango/project'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='cheer',
            field=models.ImageField(default='pro/askdjango/None/no_img.png', upload_to='pro/askdjango/project'),
        ),
    ]
