# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20170209_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='basic',
            field=models.ImageField(default='pro/askdjango/project/None/no_img.png', upload_to='pro/askdjango/project'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='cheer',
            field=models.ImageField(default='pro/askdjango/project/None/no_img.png', upload_to='pro/askdjango/project'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='etc',
            field=models.ImageField(default='pro/askdjango/project/None/no_img.png', upload_to='pro/askdjango/project'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='sight',
            field=models.ImageField(default='pro/askdjango/project/None/no_img.png', upload_to='pro/askdjango/project'),
        ),
    ]
