# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20170209_1549'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.RenameField(
            model_name='blockview',
            old_name='block',
            new_name='blocks',
        ),
        migrations.AddField(
            model_name='block',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Gujang'),
        ),
        migrations.AddField(
            model_name='gujang',
            name='basic',
            field=models.ImageField(default='pro/askdjango/project/uploads/None/no_img.png', upload_to='pro/askdjango/project/uploads'),
        ),
        migrations.AddField(
            model_name='gujang',
            name='cheer',
            field=models.ImageField(default='pro/askdjango/project/uploads/None/no_img.png', upload_to='pro/askdjango/project/uploads'),
        ),
        migrations.AddField(
            model_name='gujang',
            name='etc',
            field=models.ImageField(default='pro/askdjango/project/uploads/None/no_img.png', upload_to='pro/askdjango/project/uploads'),
        ),
        migrations.AddField(
            model_name='gujang',
            name='sight',
            field=models.ImageField(default='pro/askdjango/project/uploads/None/no_img.png', upload_to='pro/askdjango/project/uploads'),
        ),
        migrations.AddField(
            model_name='gujang',
            name='tip',
            field=models.TextField(blank=True, help_text='해시태그 형태로 구장별 팁을 제공'),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_img',
            field=models.ImageField(default='pro/askdjango/project/uploads/None/no_img.png', upload_to='pro/askdjango/project/uploads'),
        ),
        migrations.AlterField(
            model_name='blockview',
            name='view_img',
            field=models.ImageField(default='pro/askdjango/project/uploads/None/no_img.png', upload_to='pro/askdjango/project/uploads'),
        ),
        migrations.AlterField(
            model_name='gujang',
            name='logo',
            field=models.ImageField(default='pro/askdjango/project/uploads/None/no_img.png', upload_to='pro/askdjango/project/uploads'),
        ),
    ]
