# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20170209_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_img',
            field=models.ImageField(default='/uploads/None/no_img.png', upload_to='/uploads'),
        ),
        migrations.AlterField(
            model_name='blockview',
            name='view_img',
            field=models.ImageField(default='/uploads/None/no_img.png', upload_to='/uploads'),
        ),
        migrations.AlterField(
            model_name='gujang',
            name='basic',
            field=models.ImageField(default='/uploads/None/no_img.png', upload_to='/uploads'),
        ),
        migrations.AlterField(
            model_name='gujang',
            name='cheer',
            field=models.ImageField(default='/uploads/None/no_img.png', upload_to='/uploads'),
        ),
        migrations.AlterField(
            model_name='gujang',
            name='etc',
            field=models.ImageField(default='/uploads/None/no_img.png', upload_to='/uploads'),
        ),
        migrations.AlterField(
            model_name='gujang',
            name='logo',
            field=models.ImageField(default='/uploads/None/no_img.png', upload_to='/uploads'),
        ),
        migrations.AlterField(
            model_name='gujang',
            name='sight',
            field=models.ImageField(default='/uploads/None/no_img.png', upload_to='/uploads'),
        ),
    ]
