# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20170209_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blockview',
            name='view_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gujang',
            name='basic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gujang',
            name='cheer',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gujang',
            name='etc',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gujang',
            name='logo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gujang',
            name='sight',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='gujang',
            name='tip',
            field=models.TextField(blank=True),
        ),
    ]
